import turtle
import math
h = 2*(100**2)
diag = math.sqrt(h)
turtle.penup()
turtle.goto(-100,100)
turtle.pendown()
def square(t): 
    turtle.forward(t)
    turtle.right(90)
    turtle.forward(t)
    turtle.right(90)
    turtle.forward(t)
    turtle.right(90)
    turtle.forward(t)
    turtle.right(90)
square(100)


turtle.right(45)
turtle.forward(2*diag)
turtle.goto(0,0)
turtle.setheading(0)
square(100)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.right(45)
turtle.forward(diag)
turtle.penup()
turtle.goto(-100,0)
turtle.setheading(-45)
turtle.pendown()
turtle.forward(diag)
turtle.exitonclick()